server:
  port: 8002

spring:
  application:
    name: service-preco
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8431/eureka

resilience4j:
  retry:
    instances:
      service-preco:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      service-preco:
        record-exceptions:
          - feign.FeignException

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /service-preco/v3/api-docs    # âœ… JSON aqui
  swagger-ui:
    url: /service-preco/v3/api-docs