server:
  port: 8900
spring:
  application:
    name: api-gateway
  cloud:
      gateway:
        server:
          webflux:
            routes:
                # Por ordem adicionando todos os seu micro serviços, começando por 8001, 8002
              - id: service-produto
                uri: lb://service-produto
                predicates:
                  - Path=/service-produto/**
              # agora fazemos o mesmo so que com o service preco 8002
              - id: service-preco
                uri: lb://service-preco
                predicates:
                    - Path=/service-preco/**

              # por fim adicionamos o service-imposto 8003
              - id: service-imposto
                uri: lb://service-imposto
                predicates:
                  - Path=/service-imposto/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8431/eureka
springdoc:
  swagger-ui:
    urls:

        # Service produto 8001
      - name: service-produto
        url: /service-produto/v3/api-docs

        # Service preco 8002
      - name: service-preco
        url: /service-preco/v3/api-docs

        # Service imposto 8003
      - name: service-imposto
        url: /service-imposto/v3/api-docs