server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8431/eureka


spring:

  application:
    name: service-imposto
springdoc:
  api-docs:
    path: /service-imposto/v3/api-docs
  swagger-ui:
    url: /service-imposto/v3/api-docs
