server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8431/eureka

spring:
  application:
    name: service-produto

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_produto_db
    username: root
    password: admin123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

resilience4j:
  retry:
    instances:
      service-produto:
        max-attempts: 2
        wait-duration: 1s
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      service-preco:
        record-exceptions:
          - feign.FeignException